language: node_js
node_js:
  # - "node"
  # - "lts/*"
  # - "8"
  - "7"
  - "6"
  # - "5"

before_script:
  - mysql -e 'create database northwind;'
  - mysql -u root --default-character-set=utf8 northwind < sql/mysql/northwind.sql
  - psql -U postgres -c 'create database northwind;'
  - psql -U postgres -W -d northwind -f sql/pg/northwind.sql

after_success:
  - npm run coveralls
